FROM debian:bookworm-slim

## forked rtmp-module was last updated May 15, 2022
## Nginx version is from 19 Oct 2022
ARG NGINX_VERSION=1.22.1
ARG INSTALL_FFMPEG=false

## meta
LABEL org.opencontainers.image.title="Nginx compiled from source with RTMP module. Optionally installs FFmpeg."
LABEL org.opencontainers.image.authors="Athlon1600"
LABEL org.opencontainers.image.source="https://github.com/Athlon1600/nginx-rtmp-server"

## nginx compile dependencies plus optional stuff useful for debugging
RUN apt-get update && apt-get install -y build-essential libpcre3 libpcre3-dev libssl-dev \
    curl vim htop procps && \
    if [ "$INSTALL_FFMPEG" = "true" ]; then \
    curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz | tar -xJf - && \
        mv ffmpeg-*-static/ffmpeg /usr/local/bin/ && \
        mv ffmpeg-*-static/ffprobe /usr/local/bin/ && \
        rm -rf ffmpeg-*-static; \
fi && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp/build

## Download and extract nginx
RUN curl -OL https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
RUN tar -zxf nginx-${NGINX_VERSION}.tar.gz

## Original rtmp module by arut stopped updating years ago, so we use this fork instead
RUN curl -OL "https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/dev.tar.gz"
RUN tar -xvz -f "dev.tar.gz" && \
    cd nginx-${NGINX_VERSION} && \
    ./configure \
        --prefix=/usr/local/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --http-log-path=/var/log/nginx/access.log \
        --error-log-path=/var/log/nginx/error.log \
        --without-http_gzip_module \
        --with-http_ssl_module \
        --with-http_v2_module \
        --with-debug \
        --with-threads \
        --with-ipv6 \
        --add-module=../nginx-rtmp-module-dev && \
    make -j$(nproc) && \
    make install && \
    rm -rf /tmp/build

# Forward logs to Docker
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

# Set up config file
COPY nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /var/www/

# matters for long lasting RTMP connections
STOPSIGNAL SIGQUIT

EXPOSE 80
EXPOSE 1935

# CMD ["sleep", "1d"]
CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]
